
-- =====================================================
-- EXTENSIONS
-- =====================================================
create extension if not exists "pgcrypto";

-- =====================================================
-- USERS
-- =====================================================
create table public.users (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null default gen_random_uuid(),

    name text not null,
    email text unique not null,
    role text not null default 'admin',

    email_verified_at timestamp null,
    password text null,
    last_login_at timestamp null,

    account_status text not null default 'PendingInvitation',

    invitation_sent_at timestamp null,
    invitation_accepted_at timestamp null,

    remember_token text null,

    created_at timestamp default now(),
    updated_at timestamp default now()
);

-- =====================================================
-- REPORTS
-- =====================================================
create table public.reports (
    id bigserial primary key,
    uuid uuid unique not null default gen_random_uuid(),

    form_type text not null,
    school_year text not null,
    file_path text not null,
    original_filename text,
    mime_type text,
    file_size bigint,

    status text not null default 'ForAdminApproval',
    remarks text,

    submitted_by bigint references users(id) on delete set null,
    reviewed_by bigint references users(id) on delete set null,

    reviewed_at timestamp,

    archived_at timestamp null,
    archived_by bigint references users(id) on delete set null,

    created_at timestamp default now(),
    updated_at timestamp default now()
);

create index reports_status_type_year_index
on reports(status, form_type, school_year);

create index reports_archived_at_index
on reports(archived_at);

-- =====================================================
-- PERSONNELS
-- =====================================================
create table public.personnels (
    id bigserial primary key,
    uuid uuid unique not null default gen_random_uuid(),

    personnel_id_number integer unique not null,

    first_name text not null,
    middle_name text,
    last_name text not null,

    email text unique not null,
    phone_number text unique not null,

    date_of_birth date not null,
    sex text not null,

    country text,
    region text,
    province text,
    brgy_street_address text,
    city text,
    postal_code text,

    teaching_load integer,
    department text,
    position text,
    employment_status text default 'Active',

    user_id bigint unique references users(id) on delete set null,

    deleted_at timestamp,
    created_at timestamp default now(),
    updated_at timestamp default now()
);

-- =====================================================
-- SECTIONS
-- =====================================================
create table public.sections (
    id bigserial primary key,
    uuid uuid unique not null default gen_random_uuid(),

    section_name text not null,
    grade_level text not null,
    school_year text not null,

    academic_track text,
    academic_strand text,

    adviser_id bigint references personnels(id) on delete set null,

    deleted_at timestamp,

    created_at timestamp default now(),
    updated_at timestamp default now(),

    unique(section_name, grade_level, school_year)
);

create index sections_school_year_index on sections(school_year);
create index sections_grade_level_index on sections(grade_level);
create index sections_adviser_index on sections(adviser_id);

-- =====================================================
-- CLASS SCHEDULES
-- =====================================================
create table public.class_schedules (
    id bigserial primary key,
    uuid uuid unique not null default gen_random_uuid(),

    room_no text,
    subject text not null,
    school_year text not null,

    semester text,
    days jsonb not null,

    start_time time not null,
    end_time time not null,

    section_id bigint references sections(id) on delete set null,
    teacher_id bigint references personnels(id) on delete set null,

    created_at timestamp default now(),
    updated_at timestamp default now()
);

create index class_sched_teacher_index
on class_schedules(teacher_id, start_time, end_time);

create index class_sched_section_index
on class_schedules(section_id, school_year, semester);

-- =====================================================
-- LEARNERS
-- =====================================================
create table public.learners (
    id bigserial primary key,
    uuid uuid unique not null default gen_random_uuid(),

    school_year text,
    grade_to_enroll text,

    learner_type text,
    enrollment_status text default 'Pending',

    remarks text,

    section_assignment_id bigint references sections(id) on delete set null,

    has_lrn boolean default false,
    lrn text unique,

    last_name text,
    first_name text,
    middle_name text,
    name_extension text,
    birth_date date,

    sex text,
    age smallint,

    mother_tongue text,
    religion text,
    place_of_birth text,

    is_ip boolean default false,
    ip_specification text,
    is_4ps boolean default false,
    household_id_number text,
    is_pwd boolean default false,
    pwd_specification text,

    house_no_street text,
    street_name text,
    barangay text,
    municipality text,
    province text,
    country text,
    zip_code text,

    father_last_name text,
    father_first_name text,
    father_middle_name text,
    father_name_extension text,

    mother_last_name text,
    mother_first_name text,
    mother_middle_name text,
    mother_name_extension text,

    contact_number text,

    last_grade_completed text,

    previous_school_name text,
    previous_school_address text,
    date_transferred date,

    shs_academic_track text,
    shs_strand text,

    academic_track text,
    academic_strand text,

    image_usage_consent boolean default false,
    data_privacy_consent boolean default false,
    consented_at timestamp,

    reviewed_by bigint references users(id) on delete set null,
    reviewed_at timestamp,

    approved_by bigint references users(id) on delete set null,
    approved_at timestamp,

    deleted_at timestamp,

    created_at timestamp default now(),
    updated_at timestamp default now()
);

-- =====================================================
-- PASSWORD OTP
-- =====================================================
create table public.user_password_otps (
    id bigserial primary key,

    user_id bigint references users(id) on delete cascade,

    otp text not null,
    expires_at timestamp not null,
    used boolean default false,

    created_at timestamp default now(),
    updated_at timestamp default now()
);

-- =====================================================
-- NOTIFICATIONS
-- =====================================================
create table public.notifications (
    id bigserial primary key,

    user_id bigint references users(id) on delete cascade,

    type text not null,
    title text,
    message text not null,
    report_uuid uuid,

    is_read boolean default false,

    created_at timestamp default now(),
    updated_at timestamp default now()
);

-- =====================================================
-- OPTIONAL ROLE SYSTEM (simple version)
-- =====================================================
create table public.roles (
    id bigserial primary key,
    name text unique not null,
    created_at timestamp default now()
);

create table public.user_roles (
    user_id bigint references users(id) on delete cascade,
    role_id bigint references roles(id) on delete cascade,
    primary key (user_id, role_id)
);
